/**
 * Parámetros fisiológicos y de la onda arterial del caso N1.
 * Los valores clínicos del manifiesto se referencian desde este registro.
 */
import { defineParameters } from '../core/evidence';
import { windkesselShapeTable } from './windkessel';

export const FISIOLOGIA = defineParameters('fisiologia', {
  psvCms: {
    value: 90,
    unit: 'cm/s',
    range: [60, 120],
    evidence: 'documentado',
    sources: ['siemens-tcd-job-aid'],
    note: 'PSV de referencia para M1.',
  },
  edvCms: {
    value: 35,
    unit: 'cm/s',
    range: [20, 60],
    evidence: 'documentado',
    sources: ['siemens-tcd-job-aid'],
    note: 'EDV de referencia para M1.',
  },
  taMaxCms: {
    value: 55,
    unit: 'cm/s',
    range: [35, 75],
    evidence: 'derivado',
    sources: ['plan-simulador-2026'],
    note: 'Valor objetivo aproximado de la integral de la onda N1.',
  },
  piNormal: {
    value: 0.85,
    unit: 'adimensional',
    range: [0.5, 1.19],
    evidence: 'consenso',
    sources: ['gosling-pi-referencia'],
    note: 'Índice de pulsatilidad de referencia.',
  },
  lindegaardNormal: {
    value: 2,
    unit: 'adimensional',
    range: [0, 3],
    evidence: 'consenso',
    sources: ['lindegaard-indice-1989'],
    note: 'Razón ACM/ACI extracraneal normal.',
  },
  heartRateBpm: {
    value: 70,
    unit: 'lpm',
    range: [50, 100],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Frecuencia cardíaca basal del fixture N1.',
  },
  mapMmHg: {
    value: 85,
    unit: 'mmHg',
    range: [65, 110],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'PAM basal del fixture N1.',
  },
  paco2MmHg: {
    value: 40,
    unit: 'mmHg',
    range: [30, 50],
    evidence: 'consenso',
    sources: ['plan-simulador-2026'],
    note: 'PaCO₂ basal normocápnica.',
  },
  icpMmHg: {
    value: 10,
    unit: 'mmHg',
    range: [0, 15],
    evidence: 'consenso',
    sources: ['plan-simulador-2026'],
    note: 'PIC basal del fixture N1.',
  },
  ejectionFraction: {
    value: 0.3,
    unit: 'fracción de ciclo',
    range: [0.2, 0.4],
    evidence: 'consenso',
    sources: ['plan-simulador-2026'],
    note: 'Fracción temporal de eyección sistólica.',
  },
  windkesselTauS: {
    value: 0.18,
    unit: 's',
    range: [0.1, 2],
    evidence: 'consenso',
    sources: ['westerhof-windkessel-2009'],
    note: 'Constante RC del Windkessel arterial de dos elementos.',
  },
  backflowFraction: {
    value: 0.12,
    unit: 'fracción',
    range: [0, 0.3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Flujo inverso relativo durante el cierre valvular.',
  },
  backflowDurationFraction: {
    value: 0.03,
    unit: 'fracción de ciclo',
    range: [0.01, 0.08],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Duración relativa del flujo inverso y la incisura.',
  },
  respiratoryRatePerMin: {
    value: 14,
    unit: 'rpm',
    range: [8, 24],
    evidence: 'consenso',
    sources: ['plan-simulador-2026'],
    note: 'Frecuencia respiratoria basal del adulto.',
  },
  respFlowModulation: {
    value: 0.03,
    unit: 'fracción',
    range: [0, 0.1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Modulación respiratoria multiplicativa de la velocidad ACM.',
  },
  respBrainShiftMm: {
    value: 0.1,
    unit: 'mm',
    range: [0, 0.3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Desplazamiento cerebral respiratorio aproximado.',
  },
  hrvSd: {
    value: 0.02,
    unit: 'fracción de RR',
    range: [0, 0.06],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Desviación estándar relativa de los intervalos RR.',
  },
  rsaAmplitude: {
    value: 0.04,
    unit: 'fracción de RR',
    range: [0, 0.1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Amplitud de arritmia sinusal respiratoria.',
  },
  laminarProfile: {
    value: 0.85,
    unit: 'fracción',
    range: [0, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Peso del perfil laminar parabólico del vaso.',
  },
  a1PsvCms: {
    value: 80,
    unit: 'cm/s',
    range: [50, 110],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'PSV del A1 usado por el fixture.',
  },
  a1EdvCms: {
    value: 30,
    unit: 'cm/s',
    range: [15, 55],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'EDV del A1 usado por el fixture.',
  },
  p1PsvCms: {
    value: 60,
    unit: 'cm/s',
    range: [35, 90],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'PSV del P1/P2 usado por el fixture.',
  },
  p1EdvCms: {
    value: 25,
    unit: 'cm/s',
    range: [10, 45],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'EDV del P1/P2 usado por el fixture.',
  },
  qM1MlMin: {
    value: 237.76109636899673,
    unit: 'ml/min',
    range: [180, 300],
    evidence: 'derivado',
    sources: ['plan-simulador-2026'],
    note: 'Derivado con media Windkessel 0,38292: Q = vMedia·πr²·0,6, rM1=1,5 mm.',
  },
  qA2MlMin: {
    value: 92.63789745628456,
    unit: 'ml/min',
    range: [60, 130],
    evidence: 'derivado',
    sources: ['aium-tcd-guia', 'plan-simulador-2026'],
    note: 'Q terminal A2 derivado de la media Windkessel y la onda A1 de referencia, rA2=1,0 mm.',
  },
  qP2MlMin: {
    value: 87.58748421149778,
    unit: 'ml/min',
    range: [55, 125],
    evidence: 'derivado',
    sources: ['aium-tcd-guia', 'plan-simulador-2026'],
    note: 'Q terminal P2 derivado de la media Windkessel y la onda P1 de referencia, rP2=1,1 mm.',
  },
  basilarPsvCms: {
    value: 55,
    unit: 'cm/s',
    range: [30, 80],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'PSV de la basilar usado por el fixture.',
  },
  basilarEdvCms: {
    value: 22,
    unit: 'cm/s',
    range: [10, 40],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'EDV de la basilar usado por el fixture.',
  },
});

export const arterialShapeTable = windkesselShapeTable({
  periodS: 60 / FISIOLOGIA.params.heartRateBpm.value,
  ejectionFraction: FISIOLOGIA.params.ejectionFraction.value,
  tauS: FISIOLOGIA.params.windkesselTauS.value,
  backflowFraction: FISIOLOGIA.params.backflowFraction.value,
  backflowDurationFraction: FISIOLOGIA.params.backflowDurationFraction.value,
});

/** Media numérica de la onda normalizada usada para derivar los caudales. */
export function arterialShapeMean(): number {
  let sum = 0;
  for (const value of arterialShapeTable) sum += value;
  return sum / arterialShapeTable.length;
}
