/**
 * Parámetros anatómicos del caso N1: órbitas, cráneo y vasos de referencia.
 * Los puntos se mantienen escalares para que cada número tenga evidencia.
 */
import { defineParameters } from '../core/evidence';

export const ANATOMIA_OJO = defineParameters('anatomia-ojo', {
  onsdOffsetMm: {
    value: 3,
    unit: 'mm',
    range: [2.9, 3.1],
    evidence: 'consenso',
    sources: ['qcc-consenso-onsd-2024', 'montorfano-onsd-2018'],
    note: 'Medición DVNO a 3 mm retroglobo.',
  },
  globeRadiusMm: {
    value: 12,
    unit: 'mm',
    range: [11, 13.5],
    evidence: 'documentado',
    sources: ['qcc-consenso-onsd-2024'],
    note: 'Radio axial del globo adulto.',
  },
  globeRadiusJitterMm: {
    value: 0.15,
    unit: 'mm',
    range: [0, 0.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Amplitud de asimetría determinista entre ojos.',
  },
  dvnoIntDerMm: {
    value: 4.6,
    unit: 'mm',
    range: [3.5, 6],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'DVNO interno derecho del manifiesto N1.',
  },
  dvnoIntIzqMm: {
    value: 4.7,
    unit: 'mm',
    range: [3.5, 6],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'DVNO interno izquierdo del manifiesto N1.',
  },
  lensAxialMm: {
    value: 2,
    unit: 'mm',
    range: [1.5, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semiespesor axial del cristalino (grosor total 4 mm).',
  },
  lensRadialMm: {
    value: 4.6,
    unit: 'mm',
    range: [3.5, 5.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semieje radial del cristalino del fixture.',
  },
  lensAnteriorRadiusMm: {
    value: 10,
    unit: 'mm',
    range: [8, 14],
    evidence: 'consenso',
    sources: ['tablas-acusticas-estandar'],
    note: 'Radio de curvatura de la cara anterior del cristalino.',
  },
  lensPosteriorRadiusMm: {
    value: 6,
    unit: 'mm',
    range: [5, 8],
    evidence: 'consenso',
    sources: ['tablas-acusticas-estandar'],
    note: 'Radio de curvatura de la cara posterior del cristalino.',
  },
  lensEquatorMm: {
    value: 4.5,
    unit: 'mm',
    range: [4, 5],
    evidence: 'consenso',
    sources: ['tablas-acusticas-estandar'],
    note: 'Semidiámetro ecuatorial del cristalino (Ø ≈ 9 mm).',
  },
  irisApertureMm: {
    value: 1.8,
    unit: 'mm',
    range: [1, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio de abertura pupilar representada.',
  },
  nerveRadiusMm: {
    value: 1.55,
    unit: 'mm',
    range: [1.2, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio ONND del fixture.',
  },
  duraMm: {
    value: 0.35,
    unit: 'mm',
    range: [0.2, 0.6],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Grosor dural del fixture.',
  },
  sheathEcc: {
    value: 0.82,
    unit: 'adimensional',
    range: [0.7, 0.95],
    evidence: 'estimado',
    sources: ['silverman-3d-onsd-2026', 'plan-simulador-2026'],
    note: 'Razón eje menor/mayor de la vaina.',
  },
  sheathEccJitter: {
    value: 0.02,
    unit: 'adimensional',
    range: [0, 0.05],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Variación determinista bilateral de excentricidad.',
  },
  sheathTaper: {
    value: 0.15,
    unit: 'fracción',
    range: [0, 0.3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Adelgazamiento máximo de la vaina hacia el ápex.',
  },
  nerveTaper: {
    value: 0.08,
    unit: 'fracción',
    range: [0, 0.2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Adelgazamiento máximo del nervio hacia el ápex.',
  },
  centerAbsXmm: {
    value: 33,
    unit: 'mm',
    range: [28, 38],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Módulo de la coordenada lateral del centro del globo.',
  },
  centerYmm: {
    value: -2,
    unit: 'mm',
    range: [-5, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Coordenada vertical del centro del globo.',
  },
  centerZmm: {
    value: 36,
    unit: 'mm',
    range: [30, 42],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Coordenada anteroposterior del centro del globo.',
  },
  eyelidAnteriorMm: {
    value: 1.2,
    unit: 'mm',
    range: [0.5, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Separación anterior del párpado respecto al globo.',
  },
  eyelidAirGapMm: {
    value: 2.5,
    unit: 'mm',
    range: [1, 4],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Margen de aire anterior al párpado.',
  },
  eyelidLayerMm: {
    value: 3,
    unit: 'mm',
    range: [2, 5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Capa geométrica exterior del párpado.',
  },
  eyelidHalfHeightMm: {
    value: 9.5,
    unit: 'mm',
    range: [7, 12],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Media altura de la abertura palpebral.',
  },
  corneaLayerMm: {
    value: 0.55,
    unit: 'mm',
    range: [0.4, 0.8],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Espesor de la capa corneal representada.',
  },
  lensCenterOffsetMm: {
    value: 6,
    unit: 'mm',
    range: [4.5, 7.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Desplazamiento posterior del centro del cristalino.',
  },
  anteriorChamberDepthMm: {
    value: 4.4,
    unit: 'mm',
    range: [3, 6],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Profundidad anterior de cámara/iris representada.',
  },
  irisPlaneOffsetMm: {
    value: 3.6,
    unit: 'mm',
    range: [3, 5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Plano del iris respecto al polo anterior.',
  },
  irisPlaneHalfMm: {
    value: 0.2,
    unit: 'mm',
    range: [0.15, 0.4],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semigrosor axial del plano del iris (grosor 0,4 mm).',
  },
  globeWallMm: {
    value: 1.45,
    unit: 'mm',
    range: [1.0, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Espesor total de la pared (retina 0,25 + coroides 0,30 + esclera 0,90).',
  },
  sheathBulbFrac: {
    value: 0.12,
    unit: 'fracción',
    range: [0, 0.3],
    evidence: 'estimado',
    sources: ['hansen-helmke-1997', 'killer-2003'],
    note: 'Amplificación radial de la ampolla retrobulbar.',
  },
  sheathBulbCenterMm: {
    value: 2.5,
    unit: 'mm',
    range: [1, 4],
    evidence: 'estimado',
    sources: ['hansen-helmke-1997', 'killer-2003'],
    note: 'Centro de la ampolla medido desde el globo.',
  },
  sheathBulbSigmaMm: {
    value: 2.5,
    unit: 'mm',
    range: [1, 5],
    evidence: 'estimado',
    sources: ['hansen-helmke-1997', 'killer-2003'],
    note: 'Anchura axial de la ampolla retrobulbar.',
  },
  papillaRadiusMm: {
    value: 0.9,
    unit: 'mm',
    range: [0.6, 1.2],
    evidence: 'estimado',
    sources: ['jonas-lamina-2003'],
    note: 'Radio del disco papilar representado.',
  },
  laminaThicknessMm: {
    value: 0.4,
    unit: 'mm',
    range: [0.2, 0.6],
    evidence: 'estimado',
    sources: ['jonas-lamina-2003'],
    note: 'Espesor de la lámina cribosa.',
  },
  papillaCupMm: {
    value: 0.15,
    unit: 'mm',
    range: [0, 0.4],
    evidence: 'estimado',
    sources: ['jonas-lamina-2003'],
    note: 'Profundidad de excavación papilar.',
  },
  tortuosityAmpMm: {
    value: 0.35,
    unit: 'mm',
    range: [0, 1],
    evidence: 'estimado',
    sources: ['silverman-3d-onsd-2026'],
    note: 'Amplitud de la ondulación lateral del nervio.',
  },
  tortuosityPeriodMm: {
    value: 14,
    unit: 'mm',
    range: [8, 25],
    evidence: 'estimado',
    sources: ['silverman-3d-onsd-2026'],
    note: 'Periodo axial de la ondulación del nervio.',
  },
  nerveNasalBendMm: {
    value: 6,
    unit: 'mm',
    range: [3, 9],
    evidence: 'estimado',
    sources: ['silverman-3d-onsd-2026'],
    note: 'Desplazamiento nasal asintótico de la línea central.',
  },
  gazeAngleRad: {
    value: 0,
    unit: 'rad',
    range: [-0.5, 0.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Ángulo de mirada del fixture N1.',
  },
});

export const ANATOMIA_CABEZA = defineParameters('anatomia-cabeza', {
  skullCenterXmm: {
    value: 0,
    unit: 'mm',
    range: [-5, 5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Centro x del elipsoide craneal N1.',
  },
  skullCenterYmm: {
    value: 28,
    unit: 'mm',
    range: [20, 35],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Centro y del elipsoide craneal N1.',
  },
  skullCenterZmm: {
    value: -12,
    unit: 'mm',
    range: [-20, -5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Centro z del elipsoide craneal N1.',
  },
  skullRadiusXmm: {
    value: 82,
    unit: 'mm',
    range: [75, 90],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semieje lateral craneal.',
  },
  skullRadiusYmm: {
    value: 100,
    unit: 'mm',
    range: [90, 110],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semieje vertical craneal.',
  },
  skullRadiusZmm: {
    value: 96,
    unit: 'mm',
    range: [88, 105],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semieje anteroposterior craneal.',
  },
  skullThicknessMm: {
    value: 5,
    unit: 'mm',
    range: [3, 8],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Espesor óseo fuera de la ventana.',
  },
  windowThicknessMm: {
    value: 1.6,
    unit: 'mm',
    range: [1, 2.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'Espesor óseo efectivo de la ventana temporal.',
  },
  windowQuality: {
    value: 0.9,
    unit: 'fracción',
    range: [0.5, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Calidad de ventana del adulto de referencia.',
  },
  windowRadiusMm: {
    value: 18,
    unit: 'mm',
    range: [12, 25],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio útil de la ventana temporal.',
  },
  m1DepthMm: {
    value: 55,
    unit: 'mm',
    range: [40, 65],
    evidence: 'consenso',
    sources: ['siemens-tcd-job-aid', 'aium-tcd-guia'],
    note: 'Profundidad de insonación de M1 por ventana temporal.',
  },
  windowAzimuthTurns: {
    value: 0.42,
    unit: 'fracción de π',
    range: [0.3, 0.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Azimut lateral de la ventana temporal.',
  },
  windowElevationRad: {
    value: -0.18,
    unit: 'rad',
    range: [-0.5, 0],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Elevación de la ventana temporal.',
  },
  windowAnteriorFactor: {
    value: 0.35,
    unit: 'fracción',
    range: [0.1, 0.6],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Factor anteroposterior del centro de ventana.',
  },
  m1OriginXmm: {
    value: 9,
    unit: 'mm',
    range: [5, 14],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto proximal x de M1.',
  },
  m1OriginYmm: {
    value: 8,
    unit: 'mm',
    range: [5, 12],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto proximal y de M1.',
  },
  m1OriginZmm: {
    value: -6,
    unit: 'mm',
    range: [-10, 0],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto proximal z de M1.',
  },
  m1Point1Xmm: {
    value: 14,
    unit: 'mm',
    range: [10, 18],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto intermedio x de M1.',
  },
  m1Point1Ymm: {
    value: 9,
    unit: 'mm',
    range: [6, 12],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto intermedio y de M1.',
  },
  m1Point1Zmm: {
    value: -4,
    unit: 'mm',
    range: [-8, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto intermedio z de M1.',
  },
  m1Point3Xmm: {
    value: 26,
    unit: 'mm',
    range: [22, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto distal x de M1.',
  },
  m1Point3Ymm: {
    value: 10,
    unit: 'mm',
    range: [7, 13],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto distal y de M1.',
  },
  m1Point3Zmm: {
    value: 2,
    unit: 'mm',
    range: [-2, 6],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto distal z de M1.',
  },
  m1Point4Xmm: {
    value: 31,
    unit: 'mm',
    range: [27, 35],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto terminal x de M1.',
  },
  m1Point4Ymm: {
    value: 11,
    unit: 'mm',
    range: [8, 14],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto terminal y de M1.',
  },
  m1Point4Zmm: {
    value: 4,
    unit: 'mm',
    range: [0, 8],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Punto terminal z de M1.',
  },
  midbrainCenterXmm: {
    value: 0,
    unit: 'mm',
    range: [-3, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Centro x del mesencéfalo.',
  },
  midbrainCenterYmm: {
    value: 14,
    unit: 'mm',
    range: [8, 20],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Centro y del mesencéfalo.',
  },
  midbrainCenterZmm: {
    value: -12,
    unit: 'mm',
    range: [-20, -5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Centro z del mesencéfalo.',
  },
  midbrainRadiusXmm: {
    value: 17,
    unit: 'mm',
    range: [12, 22],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semieje lateral del mesencéfalo.',
  },
  midbrainRadiusYmm: {
    value: 14,
    unit: 'mm',
    range: [10, 18],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semieje vertical del mesencéfalo.',
  },
  midbrainRadiusZmm: {
    value: 24,
    unit: 'mm',
    range: [18, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Semieje anteroposterior del mesencéfalo.',
  },
  peduncleOffsetXmm: {
    value: 6,
    unit: 'mm',
    range: [4, 8],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'berg-midbrain-2008'],
    note: 'Separación lateral de los pedúnculos cerebrales.',
  },
  peduncleRadiusXmm: {
    value: 7,
    unit: 'mm',
    range: [5, 9],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'berg-midbrain-2008'],
    note: 'Semieje lateral de cada pedúnculo.',
  },
  peduncleRadiusYmm: {
    value: 6,
    unit: 'mm',
    range: [4, 8],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'berg-midbrain-2008'],
    note: 'Semieje vertical de cada pedúnculo.',
  },
  peduncleRadiusZmm: {
    value: 8,
    unit: 'mm',
    range: [6, 10],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'berg-midbrain-2008'],
    note: 'Semieje anteroposterior de cada pedúnculo.',
  },
  tegmentumRadiusXmm: {
    value: 5,
    unit: 'mm',
    range: [3, 7],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'berg-midbrain-2008'],
    note: 'Semieje lateral del tegmento central posterior.',
  },
  tegmentumRadiusYmm: {
    value: 5,
    unit: 'mm',
    range: [3, 7],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'berg-midbrain-2008'],
    note: 'Semieje vertical del tegmento.',
  },
  tegmentumRadiusZmm: {
    value: 4,
    unit: 'mm',
    range: [2, 6],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'berg-midbrain-2008'],
    note: 'Semieje anteroposterior del tegmento.',
  },
  snAreaCm2: {
    value: 0.15,
    unit: 'cm²',
    range: [0.05, 0.25],
    evidence: 'consenso',
    sources: ['berg-midbrain-2008'],
    note: 'Área axial normal de la sustancia negra.',
  },
  snHalfWidthMm: {
    value: 2,
    unit: 'mm',
    range: [1, 3],
    evidence: 'estimado',
    sources: ['berg-midbrain-2008'],
    note: 'Semieje lateral de las bandas de sustancia negra.',
  },
  snHalfDepthMm: {
    value: 5,
    unit: 'mm',
    range: [3, 7],
    evidence: 'estimado',
    sources: ['berg-midbrain-2008'],
    note: 'Semieje anteroposterior de las bandas de sustancia negra.',
  },
  snCenterYmm: {
    value: 0,
    unit: 'mm',
    range: [-2, 2],
    evidence: 'estimado',
    sources: ['berg-midbrain-2008'],
    note: 'Desplazamiento vertical de la sustancia negra respecto al mesencéfalo.',
  },
  snCenterZOffsetMm: {
    value: 6,
    unit: 'mm',
    range: [4, 8],
    evidence: 'estimado',
    sources: ['berg-midbrain-2008'],
    note: 'Desplazamiento anterior de las bandas de sustancia negra.',
  },
  redNucleusRadiusMm: {
    value: 2,
    unit: 'mm',
    range: [1, 3],
    evidence: 'estimado',
    sources: ['berg-midbrain-2008'],
    note: 'Radio de los núcleos rojos.',
  },
  thirdVentricleWidthMm: {
    value: 5,
    unit: 'mm',
    range: [3, 9],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Ancho lateral del III ventrículo.',
  },
  thirdVentricleHeightMm: {
    value: 12,
    unit: 'mm',
    range: [8, 16],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Altura vertical del III ventrículo.',
  },
  thirdVentricleDepthMm: {
    value: 20,
    unit: 'mm',
    range: [14, 26],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Profundidad anteroposterior del III ventrículo.',
  },
  ependimoThicknessMm: {
    value: 0.5,
    unit: 'mm',
    range: [0.2, 0.8],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Espesor de las paredes ependimarias.',
  },
  thalamusRadiusXmm: {
    value: 12,
    unit: 'mm',
    range: [9, 15],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Semieje lateral de cada tálamo.',
  },
  thalamusRadiusYmm: {
    value: 10,
    unit: 'mm',
    range: [7, 13],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Semieje vertical de cada tálamo.',
  },
  thalamusRadiusZmm: {
    value: 15,
    unit: 'mm',
    range: [11, 19],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Semieje anteroposterior de cada tálamo.',
  },
  thalamusCenterXmm: {
    value: 12,
    unit: 'mm',
    range: [9, 15],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Centro lateral de cada tálamo.',
  },
  pinealRadiusMm: {
    value: 4,
    unit: 'mm',
    range: [2, 6],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Radio de la glándula pineal.',
  },
  frontalHornCenterXmm: {
    value: 10,
    unit: 'mm',
    range: [8, 13],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Centro lateral de cada cuerno frontal.',
  },
  frontalHornCenterZmm: {
    value: 15,
    unit: 'mm',
    range: [10, 20],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Posición anterior de los cuernos frontales.',
  },
  frontalHornRadiusXmm: {
    value: 4,
    unit: 'mm',
    range: [2, 6],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Semieje lateral de cada cuerno frontal.',
  },
  frontalHornRadiusYmm: {
    value: 5,
    unit: 'mm',
    range: [3, 7],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Semieje vertical de cada cuerno frontal.',
  },
  frontalHornRadiusZmm: {
    value: 7.5,
    unit: 'mm',
    range: [5, 10],
    evidence: 'estimado',
    sources: ['walter-tccs-2007'],
    note: 'Semieje anteroposterior de cada cuerno frontal.',
  },
  m1RadiusMm: {
    value: 1.5,
    unit: 'mm',
    range: [1, 2.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'Radio del tubo M1 del fixture.',
  },
  a1RadiusMm: {
    value: 1.2,
    unit: 'mm',
    range: [0.8, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'Radio del tubo A1 del fixture.',
  },
  p1RadiusMm: {
    value: 1.1,
    unit: 'mm',
    range: [0.8, 1.8],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'Radio del tubo P1 del fixture.',
  },
  p2RadiusMm: {
    value: 1.1,
    unit: 'mm',
    range: [0.8, 1.8],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'Radio del tubo P2 del fixture.',
  },
  basilarRadiusMm: {
    value: 1.6,
    unit: 'mm',
    range: [1, 2.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'aium-tcd-guia'],
    note: 'Radio del tubo basilar del fixture.',
  },
  icaRadiusMm: {
    value: 1.73,
    unit: 'mm',
    range: [1.2, 2.5],
    evidence: 'derivado',
    sources: ['walter-tccs-2007', 'murray-minimum-work-1926'],
    note: 'Radio terminal de ACI, aproximado por Murray desde M1 y A1 normales.',
  },
  acoaRadiusMm: {
    value: 0.75,
    unit: 'mm',
    range: [0.4, 1.2],
    evidence: 'estimado',
    sources: ['krabbe-hartkamp-1998', 'walter-tccs-2007'],
    note: 'Radio de la arteria comunicante anterior.',
  },
  a2RadiusMm: {
    value: 1,
    unit: 'mm',
    range: [0.6, 1.5],
    evidence: 'estimado',
    sources: ['krabbe-hartkamp-1998', 'aium-tcd-guia'],
    note: 'Radio del segmento A2.',
  },
  pcoaRadiusMm: {
    value: 0.6,
    unit: 'mm',
    range: [0.3, 1],
    evidence: 'estimado',
    sources: ['krabbe-hartkamp-1998', 'aium-tcd-guia'],
    note: 'Radio normal de la comunicante posterior.',
  },
  vertebralRadiusMm: {
    value: 1.4,
    unit: 'mm',
    range: [0.9, 2],
    evidence: 'estimado',
    sources: ['walter-tccs-2007', 'aium-tcd-guia'],
    note: 'Radio del segmento V4 vertebral.',
  },
  vesselM1PointXmm: {
    value: 20,
    unit: 'mm',
    range: [15, 25],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Coordenada x del punto M1 usado como puerta N1.',
  },
  vesselM1PointYmm: {
    value: 9.5,
    unit: 'mm',
    range: [7, 12],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Coordenada y del punto M1 usado como puerta N1.',
  },
  vesselM1PointZmm: {
    value: -1,
    unit: 'mm',
    range: [-5, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Coordenada z del punto M1 usado como puerta N1.',
  },
});
