/**
 * Parámetros del modelo de Doppler pulsado y de su prescripción temporal.
 * Los límites de bucles y tamaños de buffers siguen siendo tuning de implementación.
 */
import { defineParameters } from '../core/evidence';

export const DOPPLER = defineParameters('doppler', {
  ruidoElectronico: {
    value: 0.0004,
    unit: 'fracción',
    range: [1e-5, 4e-3],
    evidence: 'extrapolacion',
    sources: ['plan-simulador-2026'],
    note: 'Ruido relativo del receptor a transmisión unitaria.',
  },
  amplitudSangre: {
    value: 6,
    unit: 'adimensional',
    range: [1, 12],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Amplitud efectiva de dispersores sanguíneos.',
  },
  scatterersTotal: {
    value: 512,
    unit: 'dispersores',
    range: [128, 2048],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Población virtual total por puerta.',
  },
  scatterersVesselMax: {
    value: 32,
    unit: 'dispersores',
    range: [8, 128],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Máximo de siembra dirigida por vasos.',
  },
  gateLateralSigmaMinMm: {
    value: 0.8,
    unit: 'mm',
    range: [0.4, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Anchura lateral mínima de la puerta.',
  },
  gateElevationSigmaMinMm: {
    value: 1.5,
    unit: 'mm',
    range: [0.8, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Anchura elevacional mínima de la puerta.',
  },
  gatePulseSigmaMinMm: {
    value: 0.4,
    unit: 'mm',
    range: [0.2, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Longitud mínima del pulso de la puerta.',
  },
  apertureAngleSigmaRad: {
    value: 0.04,
    unit: 'rad',
    range: [0, 0.15],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Dispersión angular efectiva de la apertura.',
  },
  partialWallMm: {
    value: 0.6,
    unit: 'mm',
    range: [0, 1.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Tolerancia de volumen parcial en la pared vascular.',
  },
  bloodReseedRadiusFraction: {
    value: 0.7,
    unit: 'fracción',
    range: [0.3, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio máximo de jitter para siembra de sangre.',
  },
  bloodSeedRadiusFraction: {
    value: 0.6,
    unit: 'fracción',
    range: [0.3, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio máximo de jitter de la siembra inicial vascular.',
  },
  bloodReanchorRadiusFraction: {
    value: 0.9,
    unit: 'fracción',
    range: [0.5, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio máximo de reanclaje de sangre al eje vascular.',
  },
  wallFilterDefaultHz: {
    value: 50,
    unit: 'Hz',
    range: [0, 200],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Filtro inicial de la cadena PW.',
  },
  tcdF0Mhz: {
    value: 2,
    unit: 'MHz',
    range: [1.6, 2.5],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Frecuencia de transductor transcraneal.',
  },
  defaultTemporalDepthMm: {
    value: 90,
    unit: 'mm',
    range: [70, 110],
    evidence: 'consenso',
    sources: ['siemens-tcd-job-aid', 'aium-tcd-guia'],
    note: 'Profundidad de imagen temporal de fábrica.',
  },
  defaultTemporalFocusMm: {
    value: 50,
    unit: 'mm',
    range: [40, 65],
    evidence: 'consenso',
    sources: ['siemens-tcd-job-aid'],
    note: 'Foco temporal cercano a M1.',
  },
  defaultTemporalGainDb: {
    value: 14,
    unit: 'dB',
    range: [0, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Ganancia temporal de fábrica.',
  },
  defaultTemporalDynamicRangeDb: {
    value: 55,
    unit: 'dB',
    range: [40, 80],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Rango dinámico temporal de fábrica.',
  },
  defaultTemporalPersistence: {
    value: 0.4,
    unit: 'fracción',
    range: [0, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Persistencia temporal de fábrica.',
  },
  defaultTemporalPrfHz: {
    value: 6000,
    unit: 'Hz',
    range: [3000, 10000],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'PRF temporal de fábrica.',
  },
  defaultTemporalGateMm: {
    value: 6,
    unit: 'mm',
    range: [2, 12],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Puerta temporal de fábrica.',
  },
  defaultTemporalWallFilterHz: {
    value: 100,
    unit: 'Hz',
    range: [0, 500],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Filtro de pared temporal de fábrica.',
  },
});
