/**
 * Parámetros del modelo de Doppler pulsado y de su prescripción temporal.
 * Los límites de bucles y tamaños de buffers siguen siendo tuning de implementación.
 */
import { defineParameters } from '../core/evidence';

export const DOPPLER = defineParameters('doppler', {
  ruidoElectronico: {
    value: 0.0004,
    unit: 'fracción',
    range: [1e-5, 4e-3],
    evidence: 'extrapolacion',
    sources: ['plan-simulador-2026'],
    note: 'Ruido relativo del receptor a transmisión unitaria.',
  },
  amplitudSangre: {
    value: 6,
    unit: 'adimensional',
    range: [1, 12],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Amplitud efectiva de dispersores sanguíneos.',
  },
  scatterersTotal: {
    value: 512,
    unit: 'dispersores',
    range: [128, 2048],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Población virtual total por puerta.',
  },
  scatterersVesselMax: {
    value: 32,
    unit: 'dispersores',
    range: [8, 128],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Máximo de siembra dirigida por vasos.',
  },
  gateLateralSigmaMinMm: {
    value: 0.8,
    unit: 'mm',
    range: [0.4, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Anchura lateral mínima de la puerta.',
  },
  gateElevationSigmaMinMm: {
    value: 1.5,
    unit: 'mm',
    range: [0.8, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Anchura elevacional mínima de la puerta.',
  },
  gatePulseSigmaMinMm: {
    value: 0.4,
    unit: 'mm',
    range: [0.2, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Longitud mínima del pulso de la puerta.',
  },
  apertureAngleSigmaRad: {
    value: 0.04,
    unit: 'rad',
    range: [0, 0.15],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Dispersión angular efectiva de la apertura.',
  },
  partialWallMm: {
    value: 0.6,
    unit: 'mm',
    range: [0, 1.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Tolerancia de volumen parcial en la pared vascular.',
  },
  debriefBloodFractionMin: {
    value: 0.25,
    unit: 'fracción',
    range: [0.05, 0.8],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Fracción mínima de sangre en la puerta para considerar que el PW está dentro del vaso durante el debriefing.',
  },
  debriefAngleMaxDeg: {
    value: 60,
    unit: 'grados',
    range: [45, 80],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Ángulo real máximo recomendado para la medición PW docente.',
  },
  debriefGainSaturationDb: {
    value: 25,
    unit: 'dB',
    range: [15, 35],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Ganancia a partir de la que se señala posible engrosamiento del borde de la vaina.',
  },
  debriefOffsetTargetMm: {
    value: 3,
    unit: 'mm',
    range: [2, 4],
    evidence: 'consenso',
    sources: ['qcc-consenso-onsd-2024'],
    note: 'Distancia retroglobo de referencia para DVNO.',
  },
  debriefOffsetToleranceMm: {
    value: 1,
    unit: 'mm',
    range: [0.5, 2],
    evidence: 'consenso',
    sources: ['qcc-consenso-onsd-2024'],
    note: 'Tolerancia docente alrededor de la referencia retroglobo.',
  },
  debriefMeasurementErrorMm: {
    value: 0.5,
    unit: 'mm',
    range: [0.2, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Error absoluto DVNO que dispara un hallazgo docente.',
  },
  debriefPiTolerance: {
    value: 0.25,
    unit: 'adimensional',
    range: [0.1, 0.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Tolerancia absoluta entre PI medido y esperado en el debriefing.',
  },
  beatCoverageMin: {
    value: 0.8,
    unit: 'fracción',
    range: [0.5, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Cobertura mínima del intervalo RR para incluir un latido en el resumen PW.',
  },
  bloodReseedRadiusFraction: {
    value: 0.7,
    unit: 'fracción',
    range: [0.3, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio máximo de jitter para siembra de sangre.',
  },
  bloodSeedRadiusFraction: {
    value: 0.6,
    unit: 'fracción',
    range: [0.3, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio máximo de jitter de la siembra inicial vascular.',
  },
  bloodReanchorRadiusFraction: {
    value: 0.9,
    unit: 'fracción',
    range: [0.5, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Radio máximo de reanclaje de sangre al eje vascular.',
  },
  wallFilterDefaultHz: {
    value: 50,
    unit: 'Hz',
    range: [0, 200],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Filtro inicial de la cadena PW.',
  },
  spectralFloorOffsetDb: {
    value: 6,
    unit: 'dB',
    range: [0, 12],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Margen sobre el piso adaptativo para mantener el ruido de fondo casi negro sin ocultar su textura.',
  },
  tcdF0Mhz: {
    value: 2,
    unit: 'MHz',
    range: [1.6, 2.5],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Frecuencia de transductor transcraneal.',
  },
  defaultTemporalDepthMm: {
    value: 90,
    unit: 'mm',
    range: [70, 110],
    evidence: 'consenso',
    sources: ['siemens-tcd-job-aid', 'aium-tcd-guia'],
    note: 'Profundidad de imagen temporal de fábrica.',
  },
  defaultTemporalFocusMm: {
    value: 50,
    unit: 'mm',
    range: [40, 65],
    evidence: 'consenso',
    sources: ['siemens-tcd-job-aid'],
    note: 'Foco temporal cercano a M1.',
  },
  defaultTemporalGainDb: {
    value: 14,
    unit: 'dB',
    range: [0, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Ganancia temporal de fábrica.',
  },
  defaultTemporalDynamicRangeDb: {
    value: 55,
    unit: 'dB',
    range: [40, 80],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Rango dinámico temporal de fábrica.',
  },
  defaultTemporalPersistence: {
    value: 0.4,
    unit: 'fracción',
    range: [0, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Persistencia temporal de fábrica.',
  },
  defaultTemporalPrfHz: {
    value: 6000,
    unit: 'Hz',
    range: [3000, 10000],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'PRF temporal de fábrica.',
  },
  defaultTemporalGateMm: {
    value: 6,
    unit: 'mm',
    range: [2, 12],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Puerta temporal de fábrica.',
  },
  defaultTemporalWallFilterHz: {
    value: 100,
    unit: 'Hz',
    range: [0, 500],
    evidence: 'consenso',
    sources: ['aium-tcd-guia'],
    note: 'Filtro de pared temporal de fábrica.',
  },
  wallExcursionMm: {
    value: 0.05,
    unit: 'mm',
    range: [0, 0.2],
    evidence: 'estimado',
    sources: ['evans-mcdicken-doppler-2000'],
    note: 'Excursión sistólica de la pared arterial para clutter.',
  },
  wallMotionDecayMm: {
    value: 1.5,
    unit: 'mm',
    range: [0.5, 4],
    evidence: 'estimado',
    sources: ['evans-mcdicken-doppler-2000'],
    note: 'Decaimiento radial del movimiento de pared.',
  },
  brainPulsationMm: {
    value: 0.15,
    unit: 'mm',
    range: [0, 0.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Pulsación cerebral sistólica uniforme aproximada.',
  },
  handTremorMmS: {
    value: 0.8,
    unit: 'mm/s',
    range: [0, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Amplitud por componente del temblor fisiológico de la mano.',
  },
  handDriftFastMm: {
    value: 0.35,
    unit: 'mm',
    range: [0, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Deriva lenta rápida del pulso (~0,27 Hz) por eje.',
  },
  handDriftSlowMm: {
    value: 0.6,
    unit: 'mm',
    range: [0, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Deriva lenta del pulso (~0,06 Hz) por eje.',
  },
  colorEnsemble: {
    value: 8,
    unit: 'pulsos',
    range: [4, 16],
    evidence: 'consenso',
    sources: ['aium-tcd-guia', 'evans-mcdicken-doppler-2000'],
    note: 'Número de pulsos del ensemble de Doppler color.',
  },
  colorScatterers: {
    value: 16,
    unit: 'dispersores/celda',
    range: [8, 48],
    evidence: 'estimado',
    sources: ['aium-tcd-guia', 'evans-mcdicken-doppler-2000'],
    note: 'Dispersores virtuales por celda de color.',
  },
  colorNoiseRel: {
    value: 0.05,
    unit: 'fracción',
    range: [0, 0.2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Ruido complejo relativo de la señal color.',
  },
  colorPowerThreshold: {
    value: 0.05,
    unit: 'fracción',
    range: [0, 0.1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Fracción mínima de la potencia esperada para una celda completamente sanguínea, atenuada.',
  },
  colorVarianceMax: {
    value: 0.8,
    unit: 'fracción',
    range: [0.2, 1],
    evidence: 'estimado',
    sources: ['aium-tcd-guia', 'evans-mcdicken-doppler-2000'],
    note: 'Máxima varianza Kasai admitida para pintar color.',
  },
  spectralGammaDisplay: {
    value: 0.7,
    unit: 'adimensional',
    range: [0.4, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Gamma de compresión para presentar la potencia espectral, sin alterar powerDb.',
  },
  spectralFloorPercentile: {
    value: 0.2,
    unit: 'fracción',
    range: [0.05, 0.4],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Percentil de powerDb usado como piso adaptativo de presentación.',
  },
  audioAgcTauS: {
    value: 0.5,
    unit: 's',
    range: [0.1, 2],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Constante de tiempo del control automático lento de ganancia del audio.',
  },
  audioLowpassFrac: {
    value: 0.9,
    unit: 'fracción de PRF',
    range: [0.5, 0.99],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Frecuencia de corte del paso bajo de audio relativa a PRF/2.',
  },
});
