/**
 * Parámetros físicos y de prescripción del equipo de ultrasonido.
 * Los umbrales puramente numéricos del renderer permanecen como constantes.
 */
import { defineParameters } from '../core/evidence';
import { SPEED_OF_SOUND_M_S } from '../core/units';

export const FISICA_US = defineParameters('fisica-ultrasonido', {
  soundSpeedMs: {
    value: SPEED_OF_SOUND_M_S,
    unit: 'm/s',
    range: [1450, 1600],
    evidence: 'consenso',
    sources: ['szabo-diagnostic-ultrasound-2014'],
    note: 'Velocidad de reconstrucción acústica de tejido blando.',
  },
  axialPulseMmMhz: {
    value: 2.2,
    unit: 'mm·MHz',
    range: [1.5, 3],
    evidence: 'estimado',
    sources: ['szabo-diagnostic-ultrasound-2014', 'plan-simulador-2026'],
    note: 'Ancho axial heurístico del pulso.',
  },
  beamDivergenceGamma: {
    value: 1,
    unit: 'adimensional',
    range: [0.3, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'szabo-diagnostic-ultrasound-2014'],
    note: 'Divergencia geométrica lateral de transmisión; la recepción usa foco dinámico.',
  },
  elevationDivergenceGamma: {
    value: 0.5,
    unit: 'adimensional',
    range: [0.3, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'szabo-diagnostic-ultrasound-2014'],
    note: 'Atenuación geométrica de la divergencia elevacional fuera de foco.',
  },
  sidelobeDb: {
    value: -28,
    unit: 'dB',
    range: [-40, -15],
    evidence: 'consenso',
    sources: ['szabo-diagnostic-ultrasound-2014', 'jensen-fieldii-1996'],
    note: 'Nivel de lóbulos laterales de una apodización rectangular.',
  },
  reverbRcThreshold: {
    value: 0.5,
    unit: 'adimensional',
    range: [0.15, 0.6],
    evidence: 'consenso',
    sources: ['kremkau-artifacts', 'feldman-artifacts-2009'],
    note: 'Umbral de reflexión para réplicas de reverberación.',
  },
  reverbGain: {
    value: 0.1,
    unit: 'adimensional',
    range: [0.1, 0.7],
    evidence: 'consenso',
    sources: ['kremkau-artifacts', 'feldman-artifacts-2009'],
    note: 'Ganancia de la réplica a dos profundidades de una interfaz.',
  },
  mirrorGain: {
    value: 0.05,
    unit: 'adimensional',
    range: [0.05, 0.6],
    evidence: 'consenso',
    sources: ['kremkau-artifacts', 'feldman-artifacts-2009'],
    note: 'Ganancia de la imagen especular unidimensional.',
  },
  cometStepMm: {
    value: 0.5,
    unit: 'mm',
    range: [0.2, 1],
    evidence: 'consenso',
    sources: ['kremkau-artifacts', 'feldman-artifacts-2009'],
    note: 'Separación axial de ecos de cola de cometa.',
  },
  linearApertureActiveMm: {
    value: 12,
    unit: 'mm',
    range: [8, 16],
    evidence: 'estimado',
    sources: ['hedrick-hykes-ultrasound', 'plan-simulador-2026'],
    note: 'Subapertura activa lateral de la sonda lineal ocular.',
  },
  linearElevationApertureMm: {
    value: 4,
    unit: 'mm',
    range: [2, 8],
    evidence: 'estimado',
    sources: ['hedrick-hykes-ultrasound', 'plan-simulador-2026'],
    note: 'Apertura elevacional efectiva de la sonda lineal ocular.',
  },
  linearElevationFocusMm: {
    value: 25,
    unit: 'mm',
    range: [15, 40],
    evidence: 'estimado',
    sources: ['hedrick-hykes-ultrasound', 'plan-simulador-2026'],
    note: 'Foco elevacional nominal de la sonda lineal ocular.',
  },
  sectorApertureActiveMm: {
    value: 15,
    unit: 'mm',
    range: [12, 20],
    evidence: 'estimado',
    sources: ['hedrick-hykes-ultrasound', 'plan-simulador-2026'],
    note: 'Apertura activa equivalente de la sonda sectorial.',
  },
  sectorElevationApertureMm: {
    value: 10,
    unit: 'mm',
    range: [6, 14],
    evidence: 'estimado',
    sources: ['hedrick-hykes-ultrasound', 'plan-simulador-2026'],
    note: 'Apertura elevacional efectiva de la sonda sectorial.',
  },
  sectorElevationFocusMm: {
    value: 60,
    unit: 'mm',
    range: [40, 80],
    evidence: 'estimado',
    sources: ['hedrick-hykes-ultrasound', 'plan-simulador-2026'],
    note: 'Foco elevacional nominal de la sonda sectorial.',
  },
  interfaceEpsMm: {
    value: 0.3,
    unit: 'mm',
    range: [0.1, 0.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Separación de muestreo para estimar la normal de interfaz.',
  },
  ocularMinFrequencyMhz: {
    value: 7.5,
    unit: 'MHz',
    range: [7.5, 20],
    evidence: 'consenso',
    sources: ['qcc-consenso-onsd-2024'],
    note: 'Frecuencia mínima de sonda ocular de alta frecuencia.',
  },
  ocularMaxMi: {
    value: 0.23,
    unit: 'adimensional',
    range: [0.1, 0.23],
    evidence: 'consenso',
    sources: ['aium-seguridad-ocular-2019'],
    note: 'Límite de índice mecánico para exploración ocular.',
  },
  ocularMaxTi: {
    value: 1,
    unit: 'adimensional',
    range: [0.5, 1],
    evidence: 'consenso',
    sources: ['fda-diagnostic-ultrasound-2023'],
    note: 'Límite térmico de prescripción oftálmica.',
  },
  linearPeakPressureMPa: {
    value: 2,
    unit: 'MPa',
    range: [1, 3],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Presión pico rarefaccional máxima estimada de la sonda lineal.',
  },
  sectorPeakPressureMPa: {
    value: 2.4,
    unit: 'MPa',
    range: [1, 4],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Presión pico rarefaccional máxima estimada de la sonda sectorial.',
  },
  bmodePowerMw: {
    value: 15,
    unit: 'mW',
    range: [5, 40],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Potencia acústica temporal media estimada para B-mode.',
  },
  colorPowerMw: {
    value: 60,
    unit: 'mW',
    range: [20, 120],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Potencia acústica temporal media estimada para Doppler color.',
  },
  pwPowerMw: {
    value: 120,
    unit: 'mW',
    range: [40, 240],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Potencia acústica temporal media estimada para Doppler PW.',
  },
  defaultEyeOutputPowerDb: {
    value: -3,
    unit: 'dB relativo',
    range: [-20, 0],
    evidence: 'estimado',
    sources: ['plan-simulador-2026', 'fda-diagnostic-ultrasound-2023'],
    note: 'Salida ocular calibrada al mayor paso entero que mantiene MI oftálmico ≤0,23 y TIS ≤1 con el preset de fábrica.',
  },
  defaultTemporalOutputPowerDb: {
    value: 0,
    unit: 'dB relativo',
    range: [-20, 0],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Salida temporal de fábrica relativa al máximo del transductor.',
  },
  eyeScleraRefIq: {
    value: 0.0854749,
    unit: 'iq',
    range: [0, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Media |iQ| de la ROI de esclera posterior a 0 dB sin ruido, preset ocular.',
  },
  bmodeNoiseSnrDb: {
    value: 30,
    unit: 'dB',
    range: [20, 40],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Piso gaussiano electrónico constante del receptor, 30 dB por debajo de la media |iQ| de esclera posterior a 0 dB, preset ocular.',
  },
  bmodeNoiseTemporalRelDb: {
    value: -14,
    unit: 'dB',
    range: [-30, 0],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Piso electrónico del preset transcraneal relativo al ocular; el receptor de 2 MHz integra menos ancho de banda y los equipos TCCD priorizan penetración.',
  },
  defaultEyeFrequencyMhz: {
    value: 10,
    unit: 'MHz',
    range: [7.5, 20],
    evidence: 'consenso',
    sources: ['qcc-consenso-onsd-2024'],
    note: 'Prescripción ocular del caso N1.',
  },
  defaultEyeDepthMm: {
    value: 45,
    unit: 'mm',
    range: [30, 60],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Profundidad de imagen ocular de fábrica.',
  },
  defaultEyeFocusMm: {
    value: 22,
    unit: 'mm',
    range: [15, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Foco ocular de fábrica.',
  },
  defaultEyeGainDb: {
    value: 6,
    unit: 'dB',
    range: [0, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Ganancia ocular de fábrica.',
  },
  defaultEyeDynamicRangeDb: {
    value: 60,
    unit: 'dB',
    range: [40, 80],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Rango dinámico ocular de fábrica.',
  },
  defaultEyePersistence: {
    value: 0.3,
    unit: 'fracción',
    range: [0, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Persistencia ocular de fábrica.',
  },
  defaultEyePrfHz: {
    value: 4000,
    unit: 'Hz',
    range: [1000, 5000],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'PRF Doppler ocular de fábrica (Nyquist ≈15 cm/s a 10 MHz; la ACR aliasa levemente en sístole).',
  },
  defaultEyeGateMm: {
    value: 2,
    unit: 'mm',
    range: [1, 5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Puerta ocular de fábrica.',
  },
  defaultEyeWallFilterHz: {
    value: 50,
    unit: 'Hz',
    range: [0, 200],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Filtro de pared ocular de fábrica.',
  },
  defaultTgcDb: {
    value: 0,
    unit: 'dB',
    range: [-20, 20],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Valor inicial común de los controles TGC.',
  },
});
