/**
 * Parámetros físicos y de prescripción del equipo de ultrasonido.
 * Los umbrales puramente numéricos del renderer permanecen como constantes.
 */
import { defineParameters } from '../core/evidence';

export const FISICA_US = defineParameters('fisica-ultrasonido', {
  soundSpeedMs: {
    value: 1540,
    unit: 'm/s',
    range: [1450, 1600],
    evidence: 'consenso',
    sources: ['szabo-diagnostic-ultrasound-2014'],
    note: 'Velocidad de reconstrucción acústica de tejido blando.',
  },
  axialPulseMmMhz: {
    value: 2.2,
    unit: 'mm·MHz',
    range: [1.5, 3],
    evidence: 'estimado',
    sources: ['szabo-diagnostic-ultrasound-2014', 'plan-simulador-2026'],
    note: 'Ancho axial heurístico del pulso.',
  },
  beamSigma0Coeff: {
    value: 6,
    unit: 'MHz·líneas',
    range: [4, 8],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Coeficiente heurístico de anchura lateral inicial.',
  },
  beamSigmaFloorLines: {
    value: 0.8,
    unit: 'líneas',
    range: [0.5, 1.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Suelo de anchura lateral en líneas.',
  },
  interfaceEpsMm: {
    value: 0.3,
    unit: 'mm',
    range: [0.1, 0.5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Separación de muestreo para estimar la normal de interfaz.',
  },
  ocularMinFrequencyMhz: {
    value: 7.5,
    unit: 'MHz',
    range: [7.5, 20],
    evidence: 'consenso',
    sources: ['qcc-consenso-onsd-2024'],
    note: 'Frecuencia mínima de sonda ocular de alta frecuencia.',
  },
  ocularMaxMi: {
    value: 0.23,
    unit: 'adimensional',
    range: [0.1, 0.23],
    evidence: 'consenso',
    sources: ['aium-seguridad-ocular-2019'],
    note: 'Límite de índice mecánico para exploración ocular.',
  },
  defaultEyeFrequencyMhz: {
    value: 10,
    unit: 'MHz',
    range: [7.5, 20],
    evidence: 'consenso',
    sources: ['qcc-consenso-onsd-2024'],
    note: 'Prescripción ocular del caso N1.',
  },
  defaultEyeDepthMm: {
    value: 45,
    unit: 'mm',
    range: [30, 60],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Profundidad de imagen ocular de fábrica.',
  },
  defaultEyeFocusMm: {
    value: 22,
    unit: 'mm',
    range: [15, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Foco ocular de fábrica.',
  },
  defaultEyeGainDb: {
    value: 6,
    unit: 'dB',
    range: [0, 30],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Ganancia ocular de fábrica.',
  },
  defaultEyeDynamicRangeDb: {
    value: 60,
    unit: 'dB',
    range: [40, 80],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Rango dinámico ocular de fábrica.',
  },
  defaultEyePersistence: {
    value: 0.3,
    unit: 'fracción',
    range: [0, 1],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Persistencia ocular de fábrica.',
  },
  defaultEyePrfHz: {
    value: 2500,
    unit: 'Hz',
    range: [1000, 5000],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'PRF ocular de fábrica.',
  },
  defaultEyeGateMm: {
    value: 2,
    unit: 'mm',
    range: [1, 5],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Puerta ocular de fábrica.',
  },
  defaultEyeWallFilterHz: {
    value: 50,
    unit: 'Hz',
    range: [0, 200],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Filtro de pared ocular de fábrica.',
  },
  defaultTgcDb: {
    value: 0,
    unit: 'dB',
    range: [-20, 20],
    evidence: 'estimado',
    sources: ['plan-simulador-2026'],
    note: 'Valor inicial común de los controles TGC.',
  },
});
